import { Client, Vehicle } from './types';

export const MOCK_CLIENTS: Client[] = [
  { id: 'client_1', name: 'Acme Logistics' },
  { id: 'client_2', name: 'Global Freight Co.' },
  { id: 'client_3', name: 'FastTrack Delivery' },
];

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'v1',
    clientId: 'client_1',
    type: 'Heavy',
    energySource: 'Combustão',
    coolingEquipment: false,
    fuelType: 'Diesel',
    tankCapacity: 400,
    avgConsumption: 3.5,
    licensePlate: 'ABC-1234',
    renavam: '12345678901',
    chassi: '9BWZZZ37Z4T000001',
    detranUF: 'SP',
    brand: 'Volvo',
    model: 'FH 540',
    year: 2022,
    color: 'White',
    acquisition: 'Owned',
    fipePrice: 650000,
    tracker: 'Omnilink',
    antt: '12345678',
    owner: 'Acme Logistics',
    autonomy: 1400,
    status: 'Available',
  },
  {
    id: 'v2',
    clientId: 'client_1',
    type: 'Light',
    energySource: 'Elétrico',
    coolingEquipment: true,
    coolingBrand: 'Thermo Star',
    licensePlate: 'XYZ-9876',
    renavam: '10987654321',
    chassi: '9BWZZZ37Z4T000002',
    detranUF: 'RJ',
    brand: 'Renault',
    model: 'Kangoo Z.E.',
    year: 2023,
    color: 'Silver',
    acquisition: 'Rented',
    fipePrice: 180000,
    tracker: 'Sascar',
    antt: '87654321',
    owner: 'RentACar',
    autonomy: 250,
    status: 'Available',
  },
  {
    id: 'v3',
    clientId: 'client_2',
    type: 'Cavalo',
    energySource: 'Combustão',
    coolingEquipment: false,
    semiReboque: true,
    placaSemiReboque: 'RBO-1122',
    fuelType: 'Diesel',
    tankCapacity: 600,
    avgConsumption: 2.8,
    licensePlate: 'DEF-5678',
    renavam: '11223344556',
    chassi: '9BWZZZ37Z4T000003',
    detranUF: 'MG',
    brand: 'Scania',
    model: 'R450',
    year: 2021,
    color: 'Red',
    acquisition: 'Owned',
    fipePrice: 720000,
    tracker: 'Autotrac',
    antt: '11223344',
    owner: 'Global Freight Co.',
    autonomy: 1680,
    status: 'Maintenance',
  },
];
